### ISSUE TITLE
Add higher selection of links to improve replayability

### ISSUE THREAD

**Issue by ghost** [Peter2469/Russian-Roulette#1]
1 link ain't fun, more possible links would be poggers

**Comment by Peter2469** [comment]
That can be done easily, the point of it is that it is simplistic. I will see how easy it is to setup a rickroll.

**Comment by ghost** [comment]
Great! I think I'll submit a pull request myself then.

**Comment by ghost** [comment]
Created a new pull request, it includes 2 additional links - #2

**Comment by Peter2469** [comment]
Currently, I am working to make a custom page where users can add their own "bullet" redirect and it will make a custom URL for them to send to friends/family.
